### PR TITLE
Line up branch with master

### PR DESCRIPTION
**Pull request by jewatkins**
This reverts my old cldera-tools commits that were not tagged branch specific so that we can merge master (which now has the non-tagged hooks). It then recommits that tagged branch specific hooks.

 I think this should make it easier to merge master in the future.

### CODE REVIEW

**Comment by bartgol** [comment]
Is it normal that it says there are no file changes?

**Comment by jewatkins** [comment]
It's because nothing actually gets changed after all the commits. I'm actually not sure what happens if I just try to merge master. Let me try that to see if there's conflicts.

**Comment by bartgol** [comment]
How did gh let you create the PR, if there were no changes? Usually there has to be some diff in order for the PR to be created...

**Comment by jewatkins** [comment]
yeah I get a bunch of conflicts if I try to merge master directly into the branch.

I think it's because there are changes in each commit but the final result of all commits is a branch that is up-to-date with master instead of behind.

**Comment by bartgol** [comment]
I am confused. Do we need to merge this PR then?

**Comment by jewatkins** [comment]
It's needed to make merging master into the branch easier.

I guess it depends on the workflow used to maintain this branch. i.e. do we want to keep this branch up-to-date with master.

**Comment by bartgol** [comment]
I mean that gh shows no diffs. Does the tgt branch already contain these changes?

**Review by bartgol — APPROVED** [review]

**Comment by jewatkins** [comment]
yeah but master has a different commit with similar changes so git throws conflicts when merging master.

**Pull request merged**
