### PR TITLE
Upstream merge 2022-05-31

### PR DESCRIPTION
**Pull request by brhillman**
Merge E3SM upstream into CLDERA-E3SM. Conflicts in `config_component.xml` for EAM and ELM.

### CODE REVIEW

**Review by bartgol — APPROVED** [review]
It's a huge one, so I didn't go through everything, obviously. But I did not see anything that could have affected cldera composts and the interaction with cldera-tools.

**Comment by wagmanbe** [comment]
Looks good to me, although I haven't tried to do the merge myself. Just a question, if Ben reports merge conflicts in config_components.xml, why does this pull request say "This branch has no conflicts with the base branch."

**Comment by brhillman** [comment]
> Looks good to me, although I haven't tried to do the merge myself. Just a question, if Ben reports merge conflicts in config_components.xml, why does this pull request say "This branch has no conflicts with the base branch."

Because Ben resolved the conflicts in the commit 🙂

**Comment by brhillman** [comment]
I'm getting this when trying to build tests:
```
CLDERA root DIR: /release
CMake Error at cmake/build_model.cmake:286 (find_package):
  Could not find a package configuration file provided by "Cldera" with any
  of the following names:

    ClderaConfig.cmake
    cldera-config.cmake

  Add the installation prefix of "Cldera" to CMAKE_PREFIX_PATH or set
  "Cldera_DIR" to a directory containing one of the above files.  If "Cldera"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  cmake/atm/CMakeLists.txt:1 (build_model)
```

**Comment by brhillman** [comment]
Passes tests on mappy.

**Comment by wagmanbe** [comment]
> I'm getting this when trying to build tests:
> 
> ```
> CLDERA root DIR: /release
> CMake Error at cmake/build_model.cmake:286 (find_package):
>   Could not find a package configuration file provided by "Cldera" with any
>   of the following names:
> 
>     ClderaConfig.cmake
>     cldera-config.cmake
> 
>   Add the installation prefix of "Cldera" to CMAKE_PREFIX_PATH or set
>   "Cldera_DIR" to a directory containing one of the above files.  If "Cldera"
>   provides a separate development package or SDK, be sure it has been
>   installed.
> Call Stack (most recent call first):
>   cmake/atm/CMakeLists.txt:1 (build_model)
> ```

I got the same error on master yesterday. So it is unrelated to the merge, right? I think you may have already figured that out and moved on.

**Review by wagmanbe — APPROVED** [review]
Approve merging. I did not test this by merging with my own fork.

**Comment by brhillman** [comment]
> I got the same error on master yesterday. So it is unrelated to the merge, right? I think you may have already figured that out and moved on.

Yes, @jewatkins has a PR with a fix we will merge after this goes in. I

**Pull request merged**
