### PR TITLE
Merge upstream fixes for perlmutter

### PR DESCRIPTION
**Pull request by brhillman**
Merge upstream fixes for perlmutter introduced onto E3SM/maint-2.0. Better syncing of perlmutter configuration with upstream maint-2.0 branch.

[BFB]

### CODE REVIEW

**Review by GrahamBenHarper — APPROVED** [review]
Thanks for doing this @brhillman! It all looks good to me since they're primarily `.xml` file changes, with a couple `.cmake` changes here and there. Have you tested this to see if it resolves the issues from yesterday's meeting?

**Review by wagmanbe — APPROVED** [review]
I have run this branch (without merging it into master). It compiles with debug_compile=False and it runs.

**Comment by brhillman** [comment]
@GrahamBenHarper I've tested on both pm-cpu to make sure it resolves the runtime crashes we were seeing, and on mappy to make sure it will pass nightlies, and all checks out.

**Comment by GrahamBenHarper** [comment]
That's great news! Thanks again

**Pull request merged**
