### PR TITLE
updating SAI parameter values to be up-to-date with tuned values

### PR DESCRIPTION
**Pull request by jhollowed**
submitting this PR after the discovery that the tuned parameter values were never merged to master. This should be accepted to ensure that HSW++ outputs from runs on the master branch match those that I've tuned and presented for CLDERA

### CODE REVIEW

**Comment by jewatkins** [comment]
you does it matter that the kokkos submodule is being changed here? You might need to clean that before pushing `git submodule sync --recursive && git submodule update --init --recursive`

**Comment by bartgol** [comment]
> does it matter that the kokkos submodule is being changed here? You might need to clean that before pushing `git submodule sync --recursive && git submodule update --init --recursive`

Yes, please. I'm guessing you committed everythin you had in the tree, and happened to have a not-up-to-date submodule, and git thought you wanted to actually change the submodule. I recommend doing `git reset HEAD~1`, then run the line jerry wrote, commit what's left (should be just the namelist defaults mods), then force push.

**Comment by GrahamBenHarper** [comment]
Thank you for catching this, Joe!

**Comment by jhollowed** [comment]
> does it matter that the kokkos submodule is being changed here? You might need to clean that before pushing `git submodule sync --recursive && git submodule update --init --recursive`

ah, I always screw that up. Thanks Luca and Jerry. It should be fixed now

**Comment by bartgol** [comment]
You're not alone Joe...

https://menloservice.sandia.gov/https://xkcd.com/1597/

**Pull request merged**
