### PR TITLE
Grab all fields from EAM

### PR DESCRIPTION
**Pull request by bartgol**

### CODE REVIEW

**Comment by bartgol** [comment]
Ok, this is also ready for review. It requires, of course, that the cldera installation be up to date, so it needs to be merged together with the cldera-tools one.

**Comment by jewatkins** [comment]
I get a similar error to what @asteyer gets. 
Kokkos errors after:` [CLDERA] Flushing field stats to file ...` followed by a lots of e3sm backtraces. It might be an issue in cldera-tools though and not this PR.

**Comment by bartgol** [comment]
> I get a similar error to what @asteyer gets.
> Kokkos errors after:` [CLDERA] Flushing field stats to file ...` followed by a lots of e3sm backtraces. It might be an issue in cldera-tools though and not this PR.

Does it show any errors that are not kokkos related?

**Comment by jewatkins** [comment]
> > I get a similar error to what @asteyer gets.
> > Kokkos errors after:` [CLDERA] Flushing field stats to file ...` followed by a lots of e3sm backtraces. It might be an issue in cldera-tools though and not this PR.
> 
> Does it show any errors that are not kokkos related?

Just Kokkos and the e3sm backtraces as far as I can tell. Are you not able to reproduce?

**Comment by bartgol** [comment]
I haven't tried yet. But I was hoping that other error messages might help pinpoint it. Are the Kokkos errors of the form "blah blah is being deallocated after Kokkos::finalize"? I think that's what Andrew was getting, and they point to the profiling session not being cleaned up. Since I think we _do_ clean it up, I was thinking the simulation shut down due to other errors, hence without cleaning up the Session object, and therefore causing these errors. But in that case, the real error would be whatever caused the simulation to crash in the first place.

**Comment by jewatkins** [comment]
> I haven't tried yet. But I was hoping that other error messages might help pinpoint it. Are the Kokkos errors of the form "blah blah is being deallocated after Kokkos::finalize"? I think that's what Andrew was getting, and they point to the profiling session not being cleaned up. Since I think we _do_ clean it up, I was thinking the simulation shut down due to other errors, hence without cleaning up the Session object, and therefore causing these errors. But in that case, the real error would be whatever caused the simulation to crash in the first place.

Yeah same kokkos errors. Okay, I think we were using skybridge/boca if that makes a difference. It might make sense to try mappy and/or a debug build to try to get more info.

**Comment by bartgol** [comment]
Did you look at `e3sm.log` as well as `atm.log` or just one of them?

**Comment by jewatkins** [comment]
> Did you look at `e3sm.log` as well as `atm.log` or just one of them?

This was in the e3sm log. atm log reached the end: ` ******* END OF MODEL RUN *******`

**Comment by bartgol** [comment]
Ah, that points to the profiling session not being finalized correctly. But my suspicion is that someone is finalizing kokkos, and I think it's homme.

Try changing
```
    call t_startf('cam_final')
    call cam_final( cam_out, cam_in )
    call t_stopf('cam_final')

#if defined(CLDERA_PROFILING)
    call t_startf('cldera_clean_up')
    call cldera_clean_up ()
    call t_stopf('cldera_clean_up')
#endif
```
to
```
#if defined(CLDERA_PROFILING)
    call t_startf('cldera_clean_up')
    call cldera_clean_up ()
    call t_stopf('cldera_clean_up')
#endif

    call t_startf('cam_final')
    call cam_final( cam_out, cam_in )
    call t_stopf('cam_final')
```
in `components/eam/src/cpl/atm_com_mct.F90`. I think this should fix the errors. And btw, those errors are "innocuous". Since we're at shutdown time, data will be correctly deallocated anyways. Still, if this fixes it, I can update the PR.

**Comment by bartgol** [comment]
@asteyer @GrahamBenHarper @jewatkins I strongly suspect the last commit will fix the kokkos errors.

**Review by GrahamBenHarper — APPROVED** [review]

**Pull request merged**
