### PR TITLE
Integrate HSW++ Volcanic Aerosol Injection

### PR DESCRIPTION
**Pull request by bartgol**
@jhollowed We should probably remove the instructions you added in README.md, and put them on a page on the CLDERA confluence. I assume you have access to that, but if not, let me know and I can copy paste there.

### CODE REVIEW

**Comment by bartgol** [comment]
This seems to build and run. I'm going to merge now. We can revert/adjust later if something is amiss.

**Comment by jhollowed** [comment]
Great, thanks for fixing those compiler issues @bartgol. I will move the run instructions elsewhere

**Comment by bartgol** [comment]
> Great, thanks for fixing those compiler issues @bartgol. I will move the run instructions elsewhere

I already put them on confluence, under `How-to pages`.

**Comment by jhollowed** [comment]
Excellent, thanks. I've also restored the development branch for now in case I want to stage any changes there. Else I can commit directly to master if everyone is fine with that? @brhillman

**Comment by bartgol** [comment]
IIRC, we disabled pushing directly to master.

**Pull request merged**
