### PR TITLE
Add hooks to be able to link against cldera-profiling tool

### PR DESCRIPTION
**Pull request by bartgol**
This PR adds hooks to EAM that allow to link against cldera-profiling, and call its interfaces.

Work in progress.

### CODE REVIEW

**Comment by bartgol** [comment]
@jewatkins

**Comment by jewatkins** [comment]
After @GrahamBenHarper gets the callgraph, I might start injecting a few cldera subroutines.

**Comment by GrahamBenHarper** [comment]
Sounds good! I thought I had successfully modified everything I needed by using the `xmlchange` script in E3SM, but when I tried running another test case I received a cryptic error about `TEST_MEMLEAK_TOLERANCE`. I should hopefully have it resolved this week.

**Review by GrahamBenHarper — APPROVED** [review]

**Review by GrahamBenHarper — APPROVED** [review]

**Comment by bartgol** [comment]
@GrahamBenHarper for some reason, your approval did not trigger the green check mark, even though you are part of the repo collaborators. I went ahead and merged anyways. I suspect it was a glitch, due to you not being a collaborator when the first approval happened.

Btw, you should ask to be added to sandialabs github org. I don't know who's an admin there. You can go on their page, and check though.

**Comment by GrahamBenHarper** [comment]
@bartgol I suspect my permissions in the repository aren't high enough for my approval to mean anything. Would joining the sandialabs org help with that? Are you part of the org?

**Comment by bartgol** [comment]
Ah, right, I fixed your permissions. They were 'read', now you have 'write'.

**Pull request merged**
